# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Start Graph Client
    init: pnpm run build-client
    command: pnpm run graphiql

  - name: Start Kali UI dev environment
    init: pnpm install
    command: pnpm run dev

  - name: Command Line Shell
    command: bash

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    visibility: public
    name: Kali UI
    description: Kali front end web app
    onOpen: open-browser
